### ISSUE TITLE
REDME.md typo error

### ISSUE THREAD

**Issue by fri-it2** [perfsonar/ansible-playbook-perfsonar#1]
Hi!
In README.md is a typo error:
```
Set up your invintory. Connection variables can be added here as well.

vi invintory/hosts
```
Correct:
```
Set up your inventory. Connection variables can be added here as well.

vi inventory/hosts
```
Best regards,
Tadeja

**Comment by epcjr** [comment]
FIxed!

Thanks,

-Ed

**Comment by laeti-tia** [comment]
Tadeja, thanks for reporting and Ed for fixing in https://github.com/perfsonar/ansible-playbook-perfsonar/commit/69ebd10c1d853951b3693137e3096d3e4d5eb8da  I guess we can close.
